### ISSUE TITLE
Feature: Press up key to start search with buffer.

### ISSUE THREAD

**Issue by Auratelience** [joshskidmore/zsh-fzf-history-search#19]
It would be super helpful to just press up after typing part of a command and invoke this plugin.

Thanks

**Comment by jmuchovej** [comment]
I need to look into this, but based on the following lines, I _think_ it's supported already. Just not easily readable via docs.

https://github.com/joshskidmore/zsh-fzf-history-search/blob/ba342699cee38ad20471bf9a3c60587446479741/zsh-fzf-history-search.zsh#L5-L6

**Comment by joshskidmore** [comment]
I apologize for my late response, but @jmuchovej is right. Currently, it's bound to Ctrl+r, but that key can be changed if needed (export `ZSH_FZF_HISTORY_SEARCH_BIND`). 

To reiterate the behavior (which is hopefully what you're expecting):
- When nothing is typed in the current terminal, Ctrl+r will bring forth all of your zsh history.
- If you start typing typing a command, but cannot remember the arguments of the command (or want to reference a previous command), hitting Ctrl+r will list your history, but filter it based on what you've typed so far. So, for instance, if you type `curl` then hit Ctrl+r, your zsh history will be fuzzy filtered to anything with "curl" in the entry.

I would not recommend binding the up arrow though. I feel it will cause more issues within your terminal. Ctrl+r was chosen because it's pretty standardized for viewing terminal history in some sort of way for most interactive shells.

**Comment by Auratelience** [comment]
Ok. I'll try try up-arrow and see if anything breaks. Otherwise I'll just get myself used to it.
Thanks.
