### ISSUE TITLE
Make it compatible with Antigen

### ISSUE THREAD

**Issue by hkjels** [joshskidmore/zsh-fzf-history-search#29]
I used `antigen` to install the package and it's downloaded properly, but it's not sourced. Manually sourcing works fine though. Looks like a great addition to my setup, thanks!

**Comment by Adrien-ANTON-LUDWIG** [comment]
I had the same problem. I checked `~/.antigen/init.rc` and there was no mention of this plugin.
The `init.zsh` file was not updated. To force re-writing the file you can simply delete it :

```sh
$ rm ~/.antigen/init.sh
# Open a new terminal or source .zshrc
```

I had the idea to check `init.zsh` because of a previous problem I had with antigen.
But I cannot seem to remember what it was exactly and what issue helped me.
